srcfiles = ['fileSystem.cpp',
            'pathFileSystem.cpp',
            'baseFileSystem.cpp',
            ]

Import('env')
objs = []
if len(srcfiles) > 0:
    objs += env.Object(srcfiles)

Return('objs')
