srcfiles = ['math.cpp',
            'matrix4x4.cpp',
            'quaternion.cpp',
            'matrix3.cpp',
            'transformation.cpp']
				

# MODIFICATION BELOW THIS LINE PUNISHIBLE BY SITTING IN THE SHIT CHAIR!
Import('env')
objs = []
if len(srcfiles) > 0:
    objs += env.Object(srcfiles)

Return('objs')
